services:
  nextjs:
    profiles: ["prod"]
    container_name: nextjs-app-prod
    build:
      context: ..
      dockerfile: docker/Dockerfile
    expose:
      - "3000"
    networks:
      - proxy-net

  nextjs-dev:
    profiles: ["dev"]
    image: node:20-alpine
    container_name: nextjs-app-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ../nextjs:/app
      - nextjs_node_modules:/app/node_modules
    ports:
      - "${APP_PORT}:3000"
    networks:
      - proxy-net

volumes:
  nextjs_node_modules:

networks:
  proxy-net:
    external: true
